### ISSUE TITLE
Julia 0.7 Depreciations

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/Rmath-julia#25]
Track fix `ccall` to new syntax.
`cfunction(f, r, a::Tuple) is deprecated, use cfunction(f, r, Tuple{a...})`

**Comment by nalimilan** [comment]
You could try adding `julia 0.6` to REQUIRE and see whether Femtocleaner does the job.

**Comment by Nosferican** [comment]
Femtocleaner isn't working for me for some reason. It just stopped one day. Have tried to uninstall and install it, limit it to the repo I want, etc. and no results. Is the bot up? Did the change in syntax for `cfunction` before Julia 0.6? I didn't find anything in Compat.

**Comment by KristofferC** [comment]
I think femotcleaner went offline for some reason. Not sure why.
