### ISSUE TITLE
Issue downloading and installing Rmath on windows

### ISSUE THREAD

**Issue by pclausen** [JuliaStats/Rmath-julia#38]
During installation of Gadfly I got this following error. 

```
INFO: Downloading file https://github.com/JuliaLang/Rmath-julia/releases/downloa
d/v0.2.0/libRmath-julia-win-x86_64-v0.2.0.zip
Exception calling "DownloadFile" with "2" argument(s): "The request was
aborted: Could not create SSL/TLS secure channel."
At line:1 char:1
+ (new-object
net.webclient).DownloadFile("https://github.com/JuliaLang/Rmath-juli ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

================================[ ERROR: Rmath ]================================


LoadError: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\
powershell' -NoProfile -Command '(new-object net.webclient).DownloadFile("https:
//github.com/JuliaLang/Rmath-julia/releases/download/v0.2.0/libRmath-julia-win-x
86_64-v0.2.0.zip", "C:\Users\xr3\.julia\v0.6\Rmath\deps\downloads\libRmath-julia
-win-x86_64-v0.2.0.zip")'`, ProcessExited(1)) [1]
while loading C:\Users\xr3\.julia\v0.6\Rmath\deps\build.jl, in expression starti
ng on line 47 
````

**Comment by pclausen** [comment]
The workaround was to download the file in 
https://github.com/JuliaLang/Rmath-julia/releases/download/v0.2.0/libRmath-julia-win-x86_64-v0.2.0.zip and put it into %HOME%\.julia\v0.6\Rmath\deps\downloads then run
`` Pkg.build("Rmath") ``

**Comment by nalimilan** [comment]
Sounds related to https://github.com/JuliaLang/julia/issues/26167.

**Comment by pclausen** [comment]
@nalimilan No, I had the same problem but got it fixed it with the mentioned "Easy Fix". Before that got fixed, NOTHING worked, not even `Pkg.update()` on a clean install. So I believe this problem is related to the download of the zip file (which is weird because all others packages could download without issues....).

**Comment by simonbyrne** [comment]
I think it's due to GitHub [requiring TLS 1.1+](https://githubengineering.com/crypto-removal-notice/): Rmath is one of the few package binaries which is actually hosted on GitHub (I think most other use openSUSE).

**Comment by simonbyrne** [comment]
Should be fixed now by https://github.com/JuliaLang/BinDeps.jl/pull/354
