### ISSUE TITLE
Make sampling from Hypergeometric thread-safe

### ISSUE THREAD

**Issue by adomasbaliuka** [JuliaStats/Rmath-julia#46]
This code [here](https://github.com/JuliaStats/Rmath-julia/blob/18dcd7c259b031c3ce9c275b7dd136585d126017/src/rhyper.c#L91) says the static variables "should become 'thread_local globals' ". Is there anything preventing just putting `_Thread_local` in the declaration? 

The current version leads to sampling from the hypergeometric distribution (`rhyper`) being broken when used in a threaded context. I mentioned this previously at https://github.com/JuliaStats/Distributions.jl/issues/1829.

**Comment by ViralBShah** [comment]
Happy to accept a PR as a patch file that gets applied (so that we can keep updating to new R versions and then applying the patch).

**Comment by adomasbaliuka** [comment]
I don't understand what you mean by "patch file".

**Comment by ViralBShah** [comment]
https://docs.moodle.org/dev/How_to_create_a_patch

**Comment by adomasbaliuka** [comment]
I guess that means you don't use pull requests? Fine I guess...

Before changing anything, I tried to reproduce the error explicitly in the `test.jl` file. I put this at the bottom:

```julia

@testset "rhyper" begin
    # double rhyper(double nn1in, double nn2in, double kkin)
    Nred = 30.0
    Nblue = 40.0
    Npulled = 5.0

    hyper_samples = [
        ccall((:rhyper, libRmath), Float64, (Float64, Float64, Float64), Nred, Nblue, Npulled)
        for _ in 1:1_000_000
    ]
    expected_mean = Npulled * Nred / (Nred + Nblue)
    sample_mean = sum(hyper_samples) / length(hyper_samples)
    @test sample_mean ≈ expected_mean rtol = 0.001

    N = (Nred + Nblue)
    expected_variance = Npulled * Nred * (N - Nred) * (N - Npulled) / (N * N * (N - 1))
    sample_variance = 1 / (length(hyper_samples)) * sum((hyper_samples .- sample_mean) .^ 2)
    @test sample_variance ≈ expected_variance rtol = 0.001
end

@testset "rhyper_multithreaded" begin
    # double rhyper(double nn1in, double nn2in, double kkin)
    Nred = 30.0
    Nblue = 40.0
    Npulled = 5.0

    hyper_samples = Vector{Float64}(undef, 10_000_000)
    Threads.@threads for i in eachindex(hyper_samples)
        hyper_samples[i] = ccall(
            (:rhyper, libRmath), Float64, (Float64, Float64, Float64),
            Nred, Nblue, Npulled
        )
    end

    expected_mean = Npulled * Nred / (Nred + Nblue)
    sample_mean = sum(hyper_samples) / length(hyper_samples)
    @test sample_mean ≈ expected_mean rtol = 0.001

    N = (Nred + Nblue)
    expected_variance = Npulled * Nred * (N - Nred) * (N - Npulled) / (N * N * (N - 1))
    sample_variance = 1 / (length(hyper_samples)) * sum((hyper_samples .- sample_mean) .^ 2)
    @test sample_variance ≈ expected_variance rtol = 0.001
end
```

To my surprise, this seems to work correctly even when using threads. 

That's contrary to my expectations. I'm also not sure why the [original issue](https://github.com/JuliaStats/Distributions.jl/issues/1829) with `Distributions.jl` behaves differently, since it seems to be just calling this library the same way as I do (defined [here](https://github.com/JuliaStats/Distributions.jl/blob/13029c03fa885a2b4512b954e61f9d5a7dfa0612/src/univariate/discrete/hypergeometric.jl#L92) and then [here](https://github.com/JuliaStats/StatsFuns.jl/blob/5e866baa763ff0f5d279185c1923e1cd87ea5699/src/rmath.jl#L122))

**Comment by adomasbaliuka** [comment]
And making the static variables `_Thread_local` seems to fix the issue. 

Patch:
[patch.txt](https://github.com/user-attachments/files/16573434/patch.txt)

**Comment by adomasbaliuka** [comment]
I found some more places where `static` variables seem to be intended "to be made thread-local". I did this in this new patch: 
[Uploading patch_all_statics_now_threadlocal.txt…]()

**Comment by ViralBShah** [comment]
Right we want a PR, in which this patch is applied. That way we keep carrying the patch and applying it every time we upgrade the Rmath version from the R distribution with `make update`.

**Comment by adomasbaliuka** [comment]
Do I understand correctly that you don't need anything further from me?
