### ISSUE TITLE
Whole `USEGCC`/`USECLANG` business in Make.in is unnecessary, backward and wrong

### ISSUE THREAD

**Issue by giordano** [JuliaStats/Rmath-julia#47]
> For example https://github.com/JuliaStats/Rmath-julia/blob/18dcd7c259b031c3ce9c275b7dd136585d126017/Make.inc#L16-L17 https://github.com/JuliaStats/Rmath-julia/blob/18dcd7c259b031c3ce9c275b7dd136585d126017/Make.inc#L21-L28 looks unnecessary, and wrong

_Originally posted by @giordano in https://github.com/JuliaStats/Rmath-julia/issues/44#issuecomment-2278713941_

To elaborate: the entire `USEGCC`/`USECLANG` business is unnecessary (it doesn't look it's used anywhere?) and backward (users should only need to set `CC`, if they were really needed, which they aren't here, `USEGCC`/`USECLANG` should be derived from the value of `CC`)

**Comment by giordano** [comment]
I presume the `USEGCC`/`USECLANG` dance was taken from Julia's build system, but it was wrong also there and fixed by https://github.com/JuliaLang/julia/pull/44616.  The solution here is to just delete all the lines shown above.

**Comment by ViralBShah** [comment]
I probably wrote that many years ago in the pre-BB world. What if we just get rid of Make.inc altogether and just use `$(CC)` in the makefile and let users provide whatever compiler they want by doing `make CC=clang` or `make CC=${CC}` in BB?

**Comment by ViralBShah** [comment]
Realistically, nobody outside of Yggdrasil is ever going to build this.
