### ISSUE TITLE
Non-conflicting header files

### ISSUE THREAD

**Issue by staticfloat** [JuliaStats/Rmath-julia#8]
If we want to be able to make distribution packages of this stuff, we're going to need to change our header filenames so we don't conflict with the actual Rmath package.  Perhaps `Rmath-julia.h` or similar?

**Comment by ViralBShah** [comment]
Ok, will do. It looks like we are going to need this package for a while.

**Comment by nalimilan** [comment]
I'm not sure distributions would accept a Rmath-julia package, the only change being a different RNG. They could accept a package containing the Julia package Rmath.jl including the C sources in `deps/`, though.

**Comment by staticfloat** [comment]
In any case, even if we just want to put this stuff inside of my PPA, we're
going to need to change the header names.
-E

**Comment by nalimilan** [comment]
But is Rmath-julia really useful outside of an Rmath.jl package? If it remained private in deps/, there would be no problems with conflicts.

**Comment by staticfloat** [comment]
If we want to distribute precompiled versions of package C codes,
distribution packages (.deb, .rpm, etc...) have been our go-to solution so
far.  Of course if we force the user to compile the package himself what
you propose is an option.  But so far, only Windows and OSX have isolated
binary install methods; Linux distros are all using apt/yum to install
their packages.
-E
